name: broadcast_bloc
description: An extension to the bloc state management library which adds support for broadcasting state changes to stream channels.
repository: https://github.com/felangel/broadcast_bloc
homepage: https://bloclibrary.dev
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^9.0.0
  stream_channel: ^2.0.0

dev_dependencies:
  bloc_lint: ^0.3.2
  mocktail: ^1.0.0
  test: ^1.19.2
