name: broadcast_bloc
description: An extension to the bloc state management library which adds support for broadcasting state changes to stream channels.
version: 0.1.0
repository: https://github.com/felangel/broadcast_bloc
issue_tracker: https://github.com/felangel/broadcast_bloc/issues
homepage: https://github.com/felangel/broadcast_bloc
documentation: https://bloclibrary.dev
topics: [bloc, state-management, broadcast, channel]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  stream_channel: ^2.0.0

dev_dependencies:
  bloc_lint: ^0.3.2
  mocktail: ^1.0.0
  test: ^1.19.2
