name: broadcast_bloc
description: An extension to the bloc state management library which adds support for broadcasting state changes to stream channels.
repository: https://github.com/felangel/broadcast_bloc
version: 0.1.0-dev.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.0.0
  stream_channel: ^2.0.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
